# In your netlify.toml file

[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "src"

[[redirects]]
  # CHANGE THIS LINE from "/api/*" to "/*"
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200